import { cyColors as colors } from './color-constants'
import { cyFonts } from './font-constants'
import fs from 'fs'
import path from 'path'

const GENERATED_BANNER = `/*
 * AUTO-GENERATED by css/src/generate-colors-css.ts.
 * Do not edit by hand. Run \`yarn workspace @cypress-design/css build:colors-css\`
 * after changing cyColors in color-constants.ts.
 */
`

const TOKENS_BANNER = `/*
 * AUTO-GENERATED by css/src/generate-colors-css.ts.
 * Hosted entrypoint for the full Cypress design-system token set.
 * v1: colors + typography. Spacing and other tokens will be appended
 * here in future iterations without changing the URL.
 */
`

function buildColorsCSS() {
  let css = ':root {\n'

  Object.entries(colors).forEach(([colorName, shades], index) => {
    Object.entries(shades).forEach(([shade, value]) => {
      css += `  --cy-${colorName}-${shade}: ${value.toLowerCase()};\n`
    })
    if (index < Object.keys(colors).length - 1) {
      css += '\n'
    }
  })

  css += '}\n'
  return css
}

function buildFontsCSS() {
  let css = '\n/* Typography */\n:root {\n'
  for (const [name, stack] of Object.entries(cyFonts)) {
    const value = (stack as readonly string[])
      .map((f) => (f.includes(' ') ? `"${f}"` : f))
      .join(', ')
    css += `  --cy-font-${name}: ${value};\n`
  }
  css += '}\n'
  return css
}

function generateColorsCSS() {
  const colorsCSS = buildColorsCSS()
  const fontsCSS = buildFontsCSS()

  // Internal copy consumed by the build (imported from src/index.ts).
  // Kept without the banner to preserve historical diffs/snapshots.
  fs.writeFileSync(path.join(__dirname, 'colors.css'), colorsCSS)

  // Hosted copies served at design.cypress.io/{colors,tokens}.css for
  // build-free consumers (Claude Design, plain HTML, email previews, etc.).
  const docsPublic = path.resolve(__dirname, '../../docs/public')
  fs.mkdirSync(docsPublic, { recursive: true })
  fs.writeFileSync(
    path.join(docsPublic, 'colors.css'),
    GENERATED_BANNER + colorsCSS,
  )
  fs.writeFileSync(
    path.join(docsPublic, 'tokens.css'),
    TOKENS_BANNER + colorsCSS + fontsCSS,
  )
}

generateColorsCSS()
