import * as path from 'path'
import { defineConfig } from 'vitepress'
import { globbySync } from 'globby'
import vueLiveMd from './vue-live-md-it'

// get all the components generated by vue-docgen-cli
const sidebarComponents = globbySync('components/**/*.md', {
  cwd: path.resolve(__dirname, '../'),
})

// https://vitepress.vuejs.org/config/app-configs
export default defineConfig({
  outDir: './dist',
  themeConfig: {
    sidebar: [
      {
        text: 'Components',
        items: sidebarComponents.map((comp) => {
          return {
            text: comp.replace(/^components\//, '').replace(/\.md$/, ''),
            link: comp.replace(/\.md$/, ''),
          }
        }),
      },
    ],
  },
  markdown: {
    config(md) {
      md.use(vueLiveMd)
    },
  },
})
