name: Build

on:
  workflow_call:
    inputs:
      nonce:
        type: string
        required: true

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Remove Postinstall Script
        run: npm pkg set scripts.postinstall="echo no-postinstall"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Generate icon files
        run: |
          yarn turbo run build --filter=@cypress-design/css
          yarn workspace @cypress-design/icon-registry build

      - name: Build Components
        run: |
          export NODE_OPTIONS=--max_old_space_size=4096
          yarn run build:components

      - name: Cache node_modules and built dist files
        uses: actions/cache@v4
        with:
          key: ${{ inputs.nonce }}
          path: |
            ./css/dist
            ./icon-registry/dist
            ./components
            ./node_modules
