name: Release

on:
  workflow_call:
    inputs:
      nonce:
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
      issues: read
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Restore cached build files
        id: cache-node-modules-dist
        uses: actions/cache@v4
        with:
          key: cache-${{ inputs.nonce }}
          path: |
            ./css/dist
            ./icon-registry/dist
            ./components
            ./packages/details-animation/dist
            ./node_modules

      - name: Reinstall dependencies and regenerate build files
        if: steps.cache-node-modules-dist.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
        env:
          CI: true
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Set committer info
        ## attribute the commit to cypress-bot: https://github.community/t/logging-into-git-as-a-github-app/115916
        run: |
          git config --local user.email "${{ secrets.CYPRESS_BOT_APP_ID }}+cypress-bot[bot]@users.noreply.github.com"
          git config --local user.name "cypress-bot[bot]"

      - name: Configure .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set version numbers
        run: node scripts/set-version.mjs

      - name: Remove changeset pre if it exists
        run: yarn changeset pre exit
        continue-on-error: true

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
          commit: 'ci(changesets): version packages'
          title: 'ci(changesets): version packages'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
