name: Release
on:
  push:
    branches:
      - main
      - elevatebart/action-to-release

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Yarn install
        run: yarn install

      - name: Build components
        run: yarn build:components

      - name: Publish components
        run: npx lerna publish --conventional-commits --yes
