import type { IconSet } from './constants'

import {
  cyStatusPassedSimpleX12,
  cyStatusPassedSolidX16,
  cyStatusPassedSolidX24,
  cyStatusFailedSimpleX12,
  cyStatusFailedSolidX16,
  cyStatusFailedSolidX24,
  cyStatusCancelledSolidX12,
  cyStatusCancelledSimpleX4,
  cyStatusCancelledSimpleX8,
  cyStatusErroredSimpleX4,
  cyStatusErroredSimpleX8,
  cyStatusErroredSolidX12,
  cyStatusFailedSimpleX4,
  cyStatusFailedSimpleX8,
  cyStatusPassedSimpleX4,
  cyStatusPassedSimpleX8,
  cyStatusPendingSimpleX4,
  cyStatusPendingSimpleX8,
  cyStatusPendingOutlineX12,
  cyStatusPendingOutlineX16,
  cyStatusPendingOutlineX24,
  cyStatusQueuedOutlineX12,
  cyStatusQueuedOutlineX16,
  cyStatusQueuedOutlineX24,
  cyStatusQueuedSimpleX4,
  cyStatusQueuedSimpleX8,
  cyStatusSkippedOutlineX12,
  cyStatusSkippedOutlineX16,
  cyStatusSkippedOutlineX24,
  cyStatusSkippedSimpleX4,
  cyStatusSkippedSimpleX8,
  cyStatusRunningOutlineX12,
  cyStatusRunningOutlineX16,
  cyStatusRunningOutlineX24,
  cyStatusRunningSimpleX4,
  cyStatusRunningSimpleX8,
  cyStatusPlaceholderSolidX12,
  cyStatusPlaceholderSolidX16,
  cyStatusPlaceholderSolidX24,
  cyStatusPlaceholderSimpleX4,
  cyStatusPlaceholderSimpleX8,
  cyStatusCancelledSolidX16,
  cyStatusCancelledSolidX24,
  cyStatusErroredSolidX16,
  cyStatusErroredSolidX24,
} from '@cypress-design/icon-registry'

export const statuses: Record<string, IconSet> = {
  running: {
    shouldSpin: true,
    size4Icon: cyStatusRunningSimpleX4,
    size8Icon: cyStatusRunningSimpleX8,
    size12Icon: cyStatusRunningOutlineX12,
    size16Icon: cyStatusRunningOutlineX16,
    size24Icon: cyStatusRunningOutlineX24,
  },
  passed: {
    shouldSpin: false,
    size4Icon: cyStatusPassedSimpleX4,
    size8Icon: cyStatusPassedSimpleX8,
    size12Icon: cyStatusPassedSimpleX12,
    size16Icon: cyStatusPassedSolidX16,
    size24Icon: cyStatusPassedSolidX24,
  },
  failed: {
    shouldSpin: false,
    size4Icon: cyStatusFailedSimpleX4,
    size8Icon: cyStatusFailedSimpleX8,
    size12Icon: cyStatusFailedSimpleX12,
    size16Icon: cyStatusFailedSolidX16,
    size24Icon: cyStatusFailedSolidX24,
  },
  unclaimed: {
    shouldSpin: false,
    size4Icon: cyStatusQueuedSimpleX4,
    size8Icon: cyStatusQueuedSimpleX8,
    size12Icon: cyStatusQueuedOutlineX12,
    size16Icon: cyStatusQueuedOutlineX16,
    size24Icon: cyStatusQueuedOutlineX24,
  },
  placeholder: {
    shouldSpin: false,
    size4Icon: cyStatusPlaceholderSimpleX4,
    size8Icon: cyStatusPlaceholderSimpleX8,
    size12Icon: cyStatusPlaceholderSolidX12,
    size16Icon: cyStatusPlaceholderSolidX16,
    size24Icon: cyStatusPlaceholderSolidX24,
  },
  cancelled: {
    shouldSpin: false,
    size4Icon: cyStatusCancelledSimpleX4,
    size8Icon: cyStatusCancelledSimpleX8,
    size12Icon: cyStatusCancelledSolidX12,
    size16Icon: cyStatusCancelledSolidX16,
    size24Icon: cyStatusCancelledSolidX24,
  },
  noTests: {
    shouldSpin: false,
    size4Icon: cyStatusCancelledSimpleX4,
    size8Icon: cyStatusCancelledSimpleX8,
    size12Icon: cyStatusCancelledSolidX12,
    size16Icon: cyStatusCancelledSolidX16,
    size24Icon: cyStatusCancelledSolidX24,
  },
  errored: {
    shouldSpin: false,
    size4Icon: cyStatusErroredSimpleX4,
    size8Icon: cyStatusErroredSimpleX8,
    size12Icon: cyStatusErroredSolidX12,
    size16Icon: cyStatusErroredSolidX16,
    size24Icon: cyStatusErroredSolidX24,
  },
  timedOut: {
    shouldSpin: false,
    size4Icon: cyStatusErroredSimpleX4,
    size8Icon: cyStatusErroredSimpleX8,
    size12Icon: cyStatusErroredSolidX12,
    size16Icon: cyStatusErroredSolidX16,
    size24Icon: cyStatusErroredSolidX24,
  },
  overLimit: {
    shouldSpin: false,
    size4Icon: cyStatusErroredSimpleX4,
    size8Icon: cyStatusErroredSimpleX8,
    size12Icon: cyStatusErroredSolidX12,
    size16Icon: cyStatusErroredSolidX16,
    size24Icon: cyStatusErroredSolidX24,
  },
  skipped: {
    shouldSpin: false,
    size4Icon: cyStatusSkippedSimpleX4,
    size8Icon: cyStatusSkippedSimpleX8,
    size12Icon: cyStatusSkippedOutlineX12,
    size16Icon: cyStatusSkippedOutlineX16,
    size24Icon: cyStatusSkippedOutlineX24,
  },
  pending: {
    shouldSpin: false,
    size4Icon: cyStatusPendingSimpleX4,
    size8Icon: cyStatusPendingSimpleX8,
    size12Icon: cyStatusPendingOutlineX12,
    size16Icon: cyStatusPendingOutlineX16,
    size24Icon: cyStatusPendingOutlineX24,
  },
}
